# Create a minimal golang app only container
FROM scratch
MAINTAINER Jim Conner <snafu.x@gmail.com>

#COPY ../jsonsvalidator-linux /jsonsvalidator-img
#CMD ["/jsonsvalidator-img kubernetes --verbose --kubelocal"]
